### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/yamj/api/common/http/IUserAgentSelector

### ISSUE THREAD

**Issue by danielpaten** [YAMJ/yamj-v2#2764]
With the last  (2015-08-21-1902-f92030f) java run in error :
No problem with the 2015-05-27 version
Java Version: 1.7.0_85
The error is :  Scanning directory #2, 267 files scannedjava.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/yamj/api/common/http/IUserAgentSelector
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)

**Comment by jluc2808** [comment]
idem with last 
Revision SHA: f92030f7df6cbc0160bc0aa5fc83174f59c5c5d2 
Commit Date: 2015-08-21 19:01:21 UTC
Build Date: 2015-08-21 19:02:25 UTC
Java Version: 1.8.0_60

[15:14:38 - Thread-0] MovieJukebox$2: Scanning media library T:\video\Film
[15:14:38 - main    ] ThreadExecutor: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/yamj/api/common/http/IUserAgentSelector
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.moviejukebox.tools.ThreadExecutor.waitForValues(ThreadExecutor.java:276)
	at com.moviejukebox.tools.ThreadExecutor.waitFor(ThreadExecutor.java:292)
	at com.moviejukebox.MovieJukebox.generateLibrary(MovieJukebox.java:939)
	at com.moviejukebox.MovieJukebox.main(MovieJukebox.java:469)
Caused by: java.lang.NoClassDefFoundError: org/yamj/api/common/http/IUserAgentSelector
	at com.moviejukebox.plugin.AllocinePlugin.<init>(AllocinePlugin.java:73)

......
 [15:14:38 - main    ] MovieJukebox: Found 0 videos in your media library
[15:14:38 - main    ] MovieJukebox: Stored 32807 files in the info cache
[15:14:38 - main    ] JukeboxProperties: Creating JukeboxProperties file: T:\Jukeboxes\Jukebox_eversion_evZap1.2\jukebox_details.xml
[15:14:38 - main    ] JukeboxStatistics: Creating JukeboxStatistics file: T:\Jukeboxes\Jukebox_eversion_evZap1.2\jukebox_statistics.xml
[15:14:38 - main    ] MovieJukebox: 
[15:14:38 - main    ] MovieJukebox: MovieJukebox process completed at Sun Oct 25 15:14:38 CET 2015
[15:14:38 - main    ] MovieJukebox: Processing took 00:00:04.0

checked 1rst, acces is OK, right are OK, my system w10

**Comment by jluc2808** [comment]
i tried with version 
Revision SHA: 191eccb73560108ad614c0359200e15d3ee91878 
Commit Date: 2015-04-08 08:39:35 UTC

and i havn't the problem

**Comment by danielpaten** [comment]
OK with the 2015-04-08 version it's working but not with the last version (2015-08-21)
So why this issue is closed ?
Thank for the response.

**Comment by modmax** [comment]
You can see on the date, that you use an old version (from August).
There was a problem within the build server, which has been fixed now by Ometron.

The new build should be available in several minutes ... the problem itself is fixed.

**Comment by danielpaten** [comment]
Thank you for your answer
So I'll wait a few minutes :-)

**Comment by Omertron** [comment]
The build should be complete now.

http://mediaplayersite.com/yamj_latest
