### ISSUE TITLE
FilteringLayout - Class not found

### ISSUE THREAD

**Issue by kaefert** [YAMJ/yamj-v2#2771]
Hi there!

I am trying to get YAMJ running on my Ubuntu desktop. I have not found a clear statement wether or not this software is designed to also run on Linux.

I have dowloaded `yamj-v2-2.9.tar.gz`
from https://github.com/YAMJ/yamj-v2/releases

extracted it to a new directory, and ran `mvn package` in it.
this produced `yamj-v2-2.9/distribution/target/yamj-2.9-r0000-bin.zip`
which I then unpacked in yet another new directory.

I opened this new directory and ran `bash MovieJukebox.sh` from there

This outputs on top the error:
```
log4j:ERROR Could not instantiate class [com.omertron.traileraddictapi.tools.FilteringLayout].
java.lang.ClassNotFoundException: com.omertron.traileraddictapi.tools.FilteringLayout
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.log4j.helpers.Loader.loadClass(Loader.java:198)
	at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:327)
	at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:124)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:797)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.apache.log4j.Logger.getLogger(Logger.java:117)
	at com.moviejukebox.MovieJukebox.<clinit>(MovieJukebox.java:63)
```

It continues to output more, apparently I should give it the path for my movies for it to start properly. But I wanted to ask about above exception if this should be ignored or if it is a serious problem.

**Comment by modmax** [comment]
Please download the complete distribution from:
`http://mediaplayersite.com/YAMJ_Latest`

There is always the latest build ...

**Comment by Omertron** [comment]
You must also be using java 1.7 minimum. This has to be the sun release as I don't think the openjdk version works.

**Comment by modmax** [comment]
It works with OpenJDK .. im running YAMJ2 on a linus server with installen OpenJDK 1.7 ...
