### ISSUE TITLE
some java error with fanarttv

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v2#2784]
i get error with all my series tv which report : 
[22:54:35 - Thread-3] WARN  com.moviejukebox.plugin.FanartTvPlugin  - Failed to get fanart information for IMDB ID: tt3774092 / TMDB ID: 0. Error: ExceptionType=HTTP_404_ERROR, ResponseCode=404, URL=http://webservice.fanart.tv/v3/movies/tt3774092?api_key=[APIKEY]
com.omertron.fanarttvapi.FanartTvException: ExceptionType=HTTP_404_ERROR, ResponseCode=404, URL=http://webservice.fanart.tv/v3/movies/tt3774092?api_key=52fdc988539881c2ac1f3852ddfbfc5f
	at com.omertron.fanarttvapi.FanartTvApi.requestWebPage(FanartTvApi.java:314)
	at com.omertron.fanarttvapi.FanartTvApi.getMovieArtwork(FanartTvApi.java:169)
	at com.moviejukebox.plugin.FanartTvPlugin.getMovieArtwork(FanartTvPlugin.java:350)
	at com.moviejukebox.plugin.FanartTvPlugin.scan(FanartTvPlugin.java:162)
	at com.moviejukebox.scanner.artwork.FanartTvScanner.scanOnlineArtwork(FanartTvScanner.java:70)
	at com.moviejukebox.scanner.artwork.ArtworkScanner.scan(ArtworkScanner.java:236)
	at com.moviejukebox.MovieJukebox$3.call(MovieJukebox.java:994)
	at com.moviejukebox.MovieJukebox$3.call(MovieJukebox.java:923)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at com.moviejukebox.tools.ThreadExecutor$ScheduledThread.run(ThreadExecutor.java:129)

**Comment by Omertron** [comment]
looks like a "not found" issue

**Comment by jluc2808** [comment]
yes , could that be treated with a not found message rather than a java error
