### ISSUE TITLE
Failed retrieving IMDb data for movie

### ISSUE THREAD

**Issue by shaimo** [YAMJ/yamj-v2#2786]
I'm unable to get movie info for all new movies. I'm using the newest version of yamj (2.9) and just tried it and got the following in the log file:

```
10:17:15 - Thread-1] Processing new video: Kung Fu Panda 3
[10:17:15 - Thread-1] MovieNFOScanner: Found T:\Unwatched\Kung Fu Panda 3 - 2016\Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS.nfo
[10:17:15 - Thread-1] Jukebox XML file not found: T:\Unwatched\Jukebox\Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS.xml
[10:17:15 - Thread-1] Scanning for information on Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS
[10:17:16 - Thread-1] MovieNFOScanner: Scanning NFO file for information: Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS.nfo
[10:17:16 - Thread-1] ImdbPlugin: ImdbPlugin: Scanning NFO for Imdb Id
[10:17:16 - Thread-1] ImdbPlugin: IMDb Id found in nfo: tt2267968
[10:17:16 - Thread-1] MovieNFOReader: Scanning NFO for Poster URL
[10:17:16 - Thread-1] MovieNFOReader: Failed to find any information in Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS.nfo
[10:17:16 - Thread-1] PosterScanner: No matching files found for \Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS
[10:17:16 - Thread-1] PosterScanner: Checking for 'Kung Fu Panda 3 - 2016.*' posters
[10:17:16 - Thread-1] PosterScanner: No local poster found for Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS
[10:17:16 - Thread-1] WebBrowser: Requesting http://www.imdb.com/title/tt2267968/
[10:17:17 - Thread-1] ImdbPlugin: Detected new IMDb format for 'Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS'
[10:17:17 - Thread-1] WebBrowser: Requesting http://www.imdb.com/title/tt2267968/parentalguide#certification
[10:17:17 - Thread-1] ImdbPlugin: Failed retrieving IMDb data for movie : tt2267968
[10:17:17 - Thread-1] java.lang.IllegalArgumentException: Illegal character(s) in message header field: WebBrowser: Cookie
    at sun.net.www.protocol.http.HttpURLConnection.checkMessageHeader(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.isExternalMessageHeaderAllowed(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.setRequestProperty(Unknown Source)
    at com.moviejukebox.tools.WebBrowser.sendHeader(WebBrowser.java:292)
    at com.moviejukebox.tools.WebBrowser.request(WebBrowser.java:138)
    at com.moviejukebox.tools.WebBrowser.request(WebBrowser.java:99)
    at com.moviejukebox.plugin.ImdbPlugin.updateInfoNew(ImdbPlugin.java:745)
    at com.moviejukebox.plugin.ImdbPlugin.updateImdbMediaInfo(ImdbPlugin.java:329)
    at com.moviejukebox.plugin.ImdbPlugin.scan(ImdbPlugin.java:193)
    at com.moviejukebox.plugin.DatabasePluginController.scan(DatabasePluginController.java:116)
    at com.moviejukebox.MovieJukebox.updateMovieData(MovieJukebox.java:1973)
    at com.moviejukebox.MovieJukebox$3.call(MovieJukebox.java:950)
    at com.moviejukebox.MovieJukebox$3.call(MovieJukebox.java:931)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
    at com.moviejukebox.tools.ThreadExecutor$ScheduledThread.run(ThreadExecutor.java:105)

[10:17:18 - Thread-1] Video 'Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS' was not able to be scanned using the current plugins
[10:17:18 - Thread-1] PosterScanner: Searching online for Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS
[10:17:18 - Thread-1] PosterScanner: Using themoviedb to search for a Movie poster for Kung Fu Panda 3
[10:17:18 - Thread-1] Unknown property: 'original_language' value: 'en'
[10:17:18 - Thread-1] Unknown property: 'video' value: 'false'
[10:17:19 - Thread-1] Unknown property: 'original_language' value: 'en'
[10:17:19 - Thread-1] Unknown property: 'video' value: 'false'
[10:17:19 - Thread-1] MovieDbPosterPlugin: Movie found on TheMovieDB.org: http://www.themoviedb.org/movie/140300
[10:17:19 - Thread-1] PosterScanner: Poster URL found at themoviedb: http://image.tmdb.org/t/p/original/MZFPacfKzgisnPoJIPEFZUXBBT.jpg
[10:17:19 - Thread-1] Watched Scanner: No matching files found for \Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS.mkv
[10:17:19 - Thread-1] OpenSubtitles Plugin: Skipping subtitle download for Kung Fu Panda 3, subtitles already exist: YES
[10:17:19 - Thread-1] Updating poster for: Kung Fu Panda 3
[10:17:19 - Thread-1] Downloading poster for Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS to 'Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS.jpg'
[10:17:19 - Thread-1] WebBrowser: Attempting to download 'http://image.tmdb.org/t/p/original/MZFPacfKzgisnPoJIPEFZUXBBT.jpg'
[10:17:19 - Thread-1] WebBrowser: Sucessfully downloaded 'http://image.tmdb.org/t/p/original/MZFPacfKzgisnPoJIPEFZUXBBT.jpg' to 'F:\YAMJ 2.9 new1\temp\Jukebox\Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS.jpg', Size: 1011104
[10:17:19 - Thread-1] Downloaded poster for Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS
[10:17:19 - Thread-1] ArtworkScanner (MovieArt): Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS movieart not required
[10:17:19 - Thread-1] ArtworkScanner (MovieDisc): Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS moviedisc not required
[10:17:19 - Thread-1] ArtworkScanner (MovieLogo): Kung.Fu.Panda.3.2016.1080p.BluRay.x264-SPARKS movielogo not required
[10:17:19 - Thread-1] Finished: Kung Fu Panda 3 (201/489)
```

The movie page is still created and it is indexed, etc, but what I'm basically missing is the plot, actors, etc.
Thanks for your help!

**Comment by ControllingFreak** [comment]
I also get the same problems. The YAMJ version that I was using (r2.10-SNAPSHOT-2016-01-27-2018) was working wonderfully for long time. Then the "UNKNOWN" things started. Also lost the Certification. Updated to r2.10-SNAPSHOT-2017-09-19-1318 and some titles work, some get "UNKNOWN". There is generally no Certification any longer, it's just not generated at all!
